# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        MainWindow.setStyleSheet("background-color: #09090B;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_frame = QtWidgets.QFrame(MainWindow)
        self.menu_frame.setEnabled(True)
        self.menu_frame.setMinimumSize(QtCore.QSize(268, 0))
        self.menu_frame.setMaximumSize(QtCore.QSize(268, 16777215))
        self.menu_frame.setStyleSheet("QFrame#menu_frame{\n"
                                      "    border-style: solid;\n"
                                      "    border-color: #1C1C1F;\n"
                                      "    border-right-width: 2;\n"
                                      "    background-color: #09090B;\n"
                                      "}")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setLineWidth(0)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_frame = QtWidgets.QFrame(self.menu_frame)
        self.logo_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.logo_frame.setStyleSheet("QFrame#logo_frame{\n"
                                      "    border-style: solid;\n"
                                      "    border-color: #1C1C1F;\n"
                                      "    border-bottom-width: 2;\n"
                                      "    background-color: #09090B;\n"
                                      "    border-right-width: 2;\n"
                                      "}")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setLineWidth(2)
        self.logo_frame.setObjectName("logo_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.logo_frame)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.logo_frame)
        self.logo_label.setStyleSheet("border: unset")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("assets/icons/Logo.svg"))
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_2.addWidget(self.logo_label)
        self.caminando_deprisa_label = QtWidgets.QLabel(self.logo_frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.caminando_deprisa_label.setFont(font)
        self.caminando_deprisa_label.setStyleSheet("color: #FAFAFA;\n"
                                                   "border: unset;\n"
                                                   "")
        self.caminando_deprisa_label.setObjectName("caminando_deprisa_label")
        self.horizontalLayout_2.addWidget(self.caminando_deprisa_label)
        self.verticalLayout.addWidget(self.logo_frame)
        self.options_frame = QtWidgets.QFrame(self.menu_frame)
        self.options_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.options_frame.setStyleSheet("background-color: #09090B;\n"
                                         "\n"
                                         "QFrame#loptions_frame {\n"
                                         "    border-color: #1C1C1F;\n"
                                         "    border-right-width: 2;\n"
                                         "}")
        self.options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame.setObjectName("options_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.options_frame)
        self.verticalLayout_9.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.inventario_frame = QtWidgets.QFrame(self.options_frame)
        self.inventario_frame.setStyleSheet("background-color: #09090B;")
        self.inventario_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inventario_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inventario_frame.setObjectName("inventario_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inventario_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inventario_label = QtWidgets.QLabel(self.inventario_frame)
        self.inventario_label.setMinimumSize(QtCore.QSize(0, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inventario_label.setFont(font)
        self.inventario_label.setStyleSheet("color: #FAFAFA;\n"
                                            "")
        self.inventario_label.setObjectName("inventario_label")
        self.verticalLayout_2.addWidget(self.inventario_label)
        self.inventario_button = QtWidgets.QPushButton(self.inventario_frame)
        self.inventario_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inventario_button.setFont(font)
        self.inventario_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inventario_button.setStyleSheet("QPushButton {\n"
                                             "    text-align: left;\n"
                                             "    color: #FAFAFA;\n"
                                             "    border: none;\n"
                                             "    border-radius: 7;\n"
                                             "    background-color: #09090B;\n"
                                             "    padding-left: 9;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover{\n"
                                             "    background-color: #212124;\n"
                                             "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/inventario.svg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inventario_button.setIcon(icon)
        self.inventario_button.setObjectName("inventario_button")
        self.verticalLayout_2.addWidget(self.inventario_button)
        self.agregar_precio_button = QtWidgets.QPushButton(
            self.inventario_frame)
        self.agregar_precio_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.agregar_precio_button.setFont(font)
        self.agregar_precio_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.agregar_precio_button.setStyleSheet("QPushButton {\n"
                                                 "    text-align: left;\n"
                                                 "    color: #FAFAFA;\n"
                                                 "    border: none;\n"
                                                 "    border-radius: 7;\n"
                                                 "    background-color: #09090B;\n"
                                                 "    padding-left: 9;\n"
                                                 "}\n"
                                                 "\n"
                                                 "QPushButton:hover{\n"
                                                 "    background-color: #212124;\n"
                                                 "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "assets/icons/add-price.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agregar_precio_button.setIcon(icon1)
        self.agregar_precio_button.setObjectName("agregar_precio_button")
        self.verticalLayout_2.addWidget(self.agregar_precio_button)
        self.verticalLayout_9.addWidget(self.inventario_frame)
        self.facturacion_frame = QtWidgets.QFrame(self.options_frame)
        self.facturacion_frame.setStyleSheet("background-color: #09090B;")
        self.facturacion_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.facturacion_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.facturacion_frame.setObjectName("facturacion_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.facturacion_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.facturacion_label = QtWidgets.QLabel(self.facturacion_frame)
        self.facturacion_label.setMinimumSize(QtCore.QSize(0, 0))
        self.facturacion_label.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.facturacion_label.setFont(font)
        self.facturacion_label.setStyleSheet("color: #FAFAFA;\n"
                                             "")
        self.facturacion_label.setObjectName("facturacion_label")
        self.verticalLayout_3.addWidget(self.facturacion_label)
        self.venta_button = QtWidgets.QPushButton(self.facturacion_frame)
        self.venta_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.venta_button.setFont(font)
        self.venta_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.venta_button.setStyleSheet("QPushButton {\n"
                                        "    text-align: left;\n"
                                        "    color: #FAFAFA;\n"
                                        "    border: none;\n"
                                        "    border-radius: 7;\n"
                                        "    background-color: #09090B;\n"
                                        "    padding-left: 9;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: #212124;\n"
                                        "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/dolar.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.venta_button.setIcon(icon2)
        self.venta_button.setObjectName("venta_button")
        self.verticalLayout_3.addWidget(self.venta_button)
        self.todas_las_facturas_button = QtWidgets.QPushButton(
            self.facturacion_frame)
        self.todas_las_facturas_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.todas_las_facturas_button.setFont(font)
        self.todas_las_facturas_button.setLayoutDirection(
            QtCore.Qt.LeftToRight)
        self.todas_las_facturas_button.setStyleSheet("QPushButton {\n"
                                                     "    text-align: left;\n"
                                                     "    color: #FAFAFA;\n"
                                                     "    border: none;\n"
                                                     "    border-radius: 7;\n"
                                                     "    background-color: #09090B;\n"
                                                     "    padding-left: 9;\n"
                                                     "}\n"
                                                     "\n"
                                                     "QPushButton:hover{\n"
                                                     "    background-color: #212124;\n"
                                                     "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(
            "assets/icons/history-file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.todas_las_facturas_button.setIcon(icon3)
        self.todas_las_facturas_button.setObjectName(
            "todas_las_facturas_button")
        self.verticalLayout_3.addWidget(self.todas_las_facturas_button)
        self.verticalLayout_9.addWidget(self.facturacion_frame)
        self.stock_frame = QtWidgets.QFrame(self.options_frame)
        self.stock_frame.setStyleSheet("background-color: #09090B;")
        self.stock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stock_frame.setObjectName("stock_frame")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.stock_frame)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(8)
        self.vboxlayout.setObjectName("vboxlayout")
        self.stock_label = QtWidgets.QLabel(self.stock_frame)
        self.stock_label.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stock_label.setFont(font)
        self.stock_label.setStyleSheet("color: #FAFAFA;\n"
                                       "")
        self.stock_label.setObjectName("stock_label")
        self.vboxlayout.addWidget(self.stock_label)
        self.stock_button = QtWidgets.QPushButton(self.stock_frame)
        self.stock_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stock_button.setFont(font)
        self.stock_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stock_button.setStyleSheet("QPushButton {\n"
                                        "    text-align: left;\n"
                                        "    color: #FAFAFA;\n"
                                        "    border: none;\n"
                                        "    border-radius: 7;\n"
                                        "    background-color: #09090B;\n"
                                        "    padding-left: 9;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: #212124;\n"
                                        "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/icons/stock.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stock_button.setIcon(icon4)
        self.stock_button.setObjectName("stock_button")
        self.vboxlayout.addWidget(self.stock_button)
        self.verticalLayout_9.addWidget(self.stock_frame)
        self.clientes_frame = QtWidgets.QFrame(self.options_frame)
        self.clientes_frame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.clientes_frame.setAutoFillBackground(False)
        self.clientes_frame.setStyleSheet("background-color: #09090B;")
        self.clientes_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clientes_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clientes_frame.setObjectName("clientes_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.clientes_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.clientes_label = QtWidgets.QLabel(self.clientes_frame)
        self.clientes_label.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.clientes_label.setFont(font)
        self.clientes_label.setStyleSheet("color: #FAFAFA;\n"
                                          "")
        self.clientes_label.setObjectName("clientes_label")
        self.verticalLayout_5.addWidget(self.clientes_label)
        self.clientes_button = QtWidgets.QPushButton(self.clientes_frame)
        self.clientes_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clientes_button.setFont(font)
        self.clientes_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clientes_button.setStyleSheet("QPushButton {\n"
                                           "    text-align: left;\n"
                                           "    color: #FAFAFA;\n"
                                           "    border: none;\n"
                                           "    border-radius: 7;\n"
                                           "    background-color: #09090B;\n"
                                           "    padding-left: 9;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover{\n"
                                           "    background-color: #212124;\n"
                                           "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/icons/client.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clientes_button.setIcon(icon5)
        self.clientes_button.setObjectName("clientes_button")
        self.verticalLayout_5.addWidget(self.clientes_button)
        self.verticalLayout_9.addWidget(self.clientes_frame)
        self.trabajadores_frame = QtWidgets.QFrame(self.options_frame)
        self.trabajadores_frame.setStyleSheet("background-color: #09090B;")
        self.trabajadores_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trabajadores_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trabajadores_frame.setObjectName("trabajadores_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.trabajadores_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.trabajadores_label = QtWidgets.QLabel(self.trabajadores_frame)
        self.trabajadores_label.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.trabajadores_label.setFont(font)
        self.trabajadores_label.setStyleSheet("color: #FAFAFA;\n"
                                              "")
        self.trabajadores_label.setObjectName("trabajadores_label")
        self.verticalLayout_6.addWidget(self.trabajadores_label)
        self.trabajadores_button = QtWidgets.QPushButton(
            self.trabajadores_frame)
        self.trabajadores_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trabajadores_button.setFont(font)
        self.trabajadores_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.trabajadores_button.setStyleSheet("QPushButton {\n"
                                               "    text-align: left;\n"
                                               "    color: #FAFAFA;\n"
                                               "    border: none;\n"
                                               "    border-radius: 7;\n"
                                               "    background-color: #09090B;\n"
                                               "    padding-left: 9;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:hover{\n"
                                               "    background-color: #212124;\n"
                                               "}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("assets/icons/workers.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trabajadores_button.setIcon(icon6)
        self.trabajadores_button.setObjectName("trabajadores_button")
        self.verticalLayout_6.addWidget(self.trabajadores_button)
        self.verticalLayout_9.addWidget(self.trabajadores_frame)
        self.gestion_frame = QtWidgets.QFrame(self.options_frame)
        self.gestion_frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.gestion_frame.setStyleSheet("background-color: #09090B;")
        self.gestion_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gestion_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gestion_frame.setObjectName("gestion_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gestion_frame)
        self.verticalLayout_7.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gestion_label = QtWidgets.QLabel(self.gestion_frame)
        self.gestion_label.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.gestion_label.setFont(font)
        self.gestion_label.setStyleSheet("color: #FAFAFA;\n"
                                         "")
        self.gestion_label.setObjectName("gestion_label")
        self.verticalLayout_7.addWidget(self.gestion_label)
        self.gestion_button = QtWidgets.QPushButton(self.gestion_frame)
        self.gestion_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gestion_button.setFont(font)
        self.gestion_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gestion_button.setStyleSheet("QPushButton {\n"
                                          "    text-align: left;\n"
                                          "    color: #FAFAFA;\n"
                                          "    border: none;\n"
                                          "    border-radius: 7;\n"
                                          "    background-color: #09090B;\n"
                                          "    padding-left: 9;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover{\n"
                                          "    background-color: #212124;\n"
                                          "}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(
            "assets/icons/management.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gestion_button.setIcon(icon7)
        self.gestion_button.setObjectName("gestion_button")
        self.verticalLayout_7.addWidget(self.gestion_button)
        self.verticalLayout_9.addWidget(self.gestion_frame)
        self.datos_frame = QtWidgets.QFrame(self.options_frame)
        self.datos_frame.setStyleSheet("background-color: #09090B;")
        self.datos_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.datos_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.datos_frame.setObjectName("datos_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.datos_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.datos_label = QtWidgets.QLabel(self.datos_frame)
        self.datos_label.setMinimumSize(QtCore.QSize(0, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.datos_label.setFont(font)
        self.datos_label.setStyleSheet("color: #FAFAFA;\n"
                                       "")
        self.datos_label.setObjectName("datos_label")
        self.verticalLayout_8.addWidget(self.datos_label)
        self.datos_generales_button = QtWidgets.QPushButton(self.datos_frame)
        self.datos_generales_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.datos_generales_button.setFont(font)
        self.datos_generales_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.datos_generales_button.setStyleSheet("QPushButton {\n"
                                                  "    text-align: left;\n"
                                                  "    color: #FAFAFA;\n"
                                                  "    border: none;\n"
                                                  "    border-radius: 7;\n"
                                                  "    background-color: #09090B;\n"
                                                  "    padding-left: 9;\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:hover{\n"
                                                  "    background-color: #212124;\n"
                                                  "}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("assets/icons/building.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.datos_generales_button.setIcon(icon8)
        self.datos_generales_button.setObjectName("datos_generales_button")
        self.verticalLayout_8.addWidget(self.datos_generales_button)
        self.descuento_button = QtWidgets.QPushButton(self.datos_frame)
        self.descuento_button.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.descuento_button.setFont(font)
        self.descuento_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.descuento_button.setStyleSheet("QPushButton {\n"
                                            "    text-align: left;\n"
                                            "    color: #FAFAFA;\n"
                                            "    border: none;\n"
                                            "    border-radius: 7;\n"
                                            "    background-color: #09090B;\n"
                                            "    padding-left: 9;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover{\n"
                                            "    background-color: #212124;\n"
                                            "}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("assets/icons/discount.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.descuento_button.setIcon(icon9)
        self.descuento_button.setObjectName("descuento_button")
        self.verticalLayout_8.addWidget(self.descuento_button)
        self.verticalLayout_9.addWidget(self.datos_frame)
        self.verticalLayout.addWidget(self.options_frame)
        spacerItem = QtWidgets.QSpacerItem(
            20, 117, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.role_frame = QtWidgets.QFrame(self.menu_frame)
        self.role_frame.setMinimumSize(QtCore.QSize(0, 45))
        self.role_frame.setStyleSheet("background-color: #09090B;")
        self.role_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.role_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.role_frame.setObjectName("role_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.role_frame)
        self.horizontalLayout_4.setContentsMargins(9, 2, 32, 2)
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.user_avatar_label = QtWidgets.QLabel(self.role_frame)
        self.user_avatar_label.setText("")
        self.user_avatar_label.setPixmap(
            QtGui.QPixmap("assets/img/user.png"))
        self.user_avatar_label.setObjectName("user_avatar_label")
        self.horizontalLayout_4.addWidget(self.user_avatar_label)
        self.user_verticalLayout = QtWidgets.QVBoxLayout()
        self.user_verticalLayout.setSpacing(0)
        self.user_verticalLayout.setObjectName("user_verticalLayout")
        self.user_label = QtWidgets.QLabel(self.role_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.user_label.setFont(font)
        self.user_label.setStyleSheet("color: #E6E6E6;")
        self.user_label.setObjectName("user_label")
        self.user_verticalLayout.addWidget(self.user_label)
        self.rol_horizontalLayout = QtWidgets.QHBoxLayout()
        self.rol_horizontalLayout.setSpacing(2)
        self.rol_horizontalLayout.setObjectName("rol_horizontalLayout")
        self.rol_abel = QtWidgets.QLabel(self.role_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rol_abel.setFont(font)
        self.rol_abel.setStyleSheet("color: #9797A0;")
        self.rol_abel.setObjectName("rol_abel")
        self.rol_horizontalLayout.addWidget(self.rol_abel)
        self.exit_label = QtWidgets.QLabel(self.role_frame)
        self.exit_label.setText("")
        self.exit_label.setPixmap(QtGui.QPixmap("assets/icons/exit.svg"))
        self.exit_label.setObjectName("exit_label")
        self.rol_horizontalLayout.addWidget(self.exit_label)
        self.user_verticalLayout.addLayout(self.rol_horizontalLayout)
        self.horizontalLayout_4.addLayout(self.user_verticalLayout)
        self.verticalLayout.addWidget(self.role_frame)
        self.horizontalLayout.addWidget(self.menu_frame)
        self.stackedWidget = QtWidgets.QStackedWidget(MainWindow)
        self.stackedWidget.setStyleSheet("background-color: white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidget.setStyleSheet(
            """
            QStackedWidget#stackedWidget {
                background-color: #09090B;
            }
            """
        )
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Caminando deprisa"))
        self.caminando_deprisa_label.setText(
            _translate("MainWindow", "Caminando deprisa"))
        self.inventario_label.setText(_translate("MainWindow", "Inventario"))
        self.inventario_button.setText(_translate("MainWindow", "Inventario"))
        self.agregar_precio_button.setText(
            _translate("MainWindow", "Agregar precio"))
        self.facturacion_label.setText(_translate("MainWindow", "Facturación"))
        self.venta_button.setText(_translate("MainWindow", "Venta"))
        self.todas_las_facturas_button.setText(
            _translate("MainWindow", "Todas las facturas"))
        self.stock_label.setText(_translate("MainWindow", "Stock"))
        self.stock_button.setText(_translate("MainWindow", "Stock"))
        self.clientes_label.setText(_translate("MainWindow", "Clientes"))
        self.clientes_button.setText(_translate("MainWindow", "Clientes"))
        self.trabajadores_label.setText(
            _translate("MainWindow", "Trabajadores"))
        self.trabajadores_button.setText(
            _translate("MainWindow", "Trabajadores"))
        self.gestion_label.setText(_translate("MainWindow", "Gestión"))
        self.gestion_button.setText(_translate(
            "MainWindow", "Gestión de elementos"))
        self.datos_label.setText(_translate("MainWindow", "Datos"))
        self.datos_generales_button.setText(
            _translate("MainWindow", "Datos generales"))
        self.descuento_button.setText(
            _translate("MainWindow", "Descuento y IVA"))
        self.user_label.setText(_translate("MainWindow", "Osmar Adrian Mora"))
        self.rol_abel.setText(_translate("MainWindow", "Admin"))
